import React, { useEffect, useState } from "react";
import { getEarnerById } from "../../api/public-payroll-api";
import { useRouter } from "next/router";
import { CircularProgress } from "@material-ui/core";
import Head from "next/head";
import EarnerDetailCard from "./earner-detail.card";

export default function Earner() {
  const router = useRouter();
  const { eid } = router.query;
  const [employee, setEmployee] = useState();
  useEffect(() => {
    async function fetchData(employeeId: string) {
      const employeeResponse = await getEarnerById(employeeId);
      setEmployee(employeeResponse);
    }
    if (typeof eid === "string") {
      fetchData(eid).then();
    }
  }, [eid]);

  return employee ? (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <EarnerDetailCard employee={employee} />
    </div>
  ) : (
    <CircularProgress />
  );
}
