import Head from "next/head";
import { useEffect, useState } from "react";
import { getAgenciesByName } from "../api/public-payroll-api";
import MaterialTable from "material-table";

export default function Home() {
  const [agencies, setAgencies] = useState([]);
  useEffect(() => {
    async function fetchData() {
      const agencyResponse = await getAgenciesByName();
      setAgencies(agencyResponse);
    }

    fetchData().then();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>

      <MaterialTable
        title={"Agencies"}
        columns={[
          { field: "id", title: "id", hidden: true },
          { field: "name", title: "Agency" },
          {
            field: "employeeCount",
            title: "Employees",
            type: "numeric",
          },
          {
            field: "topPay",
            title: "Top Pay",
            defaultSort: "desc",
            type: "currency",
          },
          { field: "medianPay", title: "Median Pay", type: "currency" },
          {
            field: "year",
            title: "Year",
            align: "right",
          },
        ]}
        data={agencies}
        options={{ pageSize: 10 }}
      />
    </div>
  );
}
