import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import {
  getAgenciesByName,
  getTopEarnersByDepartment,
} from "../api/public-payroll-api";
import MaterialTable from "material-table";
import SearchAppBar from "./AppSearchBar";

export default function Home() {
  const router = useRouter();
  const [agencies, setAgencies] = useState([]);
  const [employees, setEmployees] = useState([]);
  useEffect(() => {
    async function fetchData() {
      const [agencyResponse, employees] = await Promise.all([
        getAgenciesByName(),
        getTopEarnersByDepartment(),
      ]);
      setAgencies(agencyResponse);
      setEmployees(employees);
    }

    fetchData().then();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <div className="app-bar-container">
        <SearchAppBar />
      </div>

      <div className="agency-table-container">
        <MaterialTable
          title={"Agencies"}
          columns={[
            { field: "id", title: "id", hidden: true },
            { field: "name", title: "Agency" },
            {
              field: "employeeCount",
              title: "Employees",
              type: "numeric",
            },
            {
              field: "topPay",
              title: "Top Pay",
              defaultSort: "desc",
              type: "currency",
            },
            { field: "medianPay", title: "Median Pay", type: "currency" },
            {
              field: "year",
              title: "Year",
              align: "right",
            },
          ]}
          data={agencies}
          options={{ pageSize: 10 }}
          // @ts-ignore
          onRowClick={(event, { id }) => {
            event?.preventDefault();
            router.push(`/agencies/${id}`);
          }}
        />
      </div>
      <div className="top-earners-container">
        <MaterialTable
          title={"Top Earners"}
          columns={[
            { field: "id", hidden: true },
            { field: "name", title: "Name" },
            { field: "jobTitle", title: "Title" },
            { field: "agency", title: "Agency" },
            { field: "totalAnnualAmount", title: "Pay", type: "currency" },
            { field: "year", title: "Year", type: "numeric" },
            { field: "originalHireDate", title: "Hire Date", align: "right" },
          ]}
          data={employees}
          options={{ pageSize: 10 }}
        />
      </div>
    </div>
  );
}
